import { armyKeys, commandCardKeys, unitCardKeys } from './keys';
import {
  ownedArmiesQueryOptions,
  ownedArmyByIdQueryOptions,
  useArchiveOwnedArmyMutation,
  useCreateOwnedArmyMutation,
  useOwnedArmiesQuery,
  useOwnedArmyByIdQuery,
  useUpdateOwnedArmyMutation,
} from './armies';
import { useCreateVsBotGameMutation } from './games';
import {
  allCommandCardsQueryOptions,
  commandCardByIdQueryOptions,
  commandCardsByIdsQueryOptions,
  currentCommandCardsQueryOptions,
  useAllCommandCardsQuery,
  useCertifyLatestCommandCardVersionsMutation,
  useCommandCardByIdQuery,
  useCommandCardsByIdsQuery,
  useCreateCommandCardVersionMutation,
  useCreateEmptyCommandCardMutation,
  useCurrentCommandCardsQuery,
  useDeleteEmptyCommandCardsMutation,
  usePreviewCommandCardMutation,
} from './commandCards';
import {
  allUnitCardsQueryOptions,
  currentUnitCardsQueryOptions,
  unitCardByIdQueryOptions,
  unitCardsByIdsQueryOptions,
  useAllUnitCardsQuery,
  useCertifyLatestUnitCardVersionsMutation,
  useCreateEmptyUnitCardMutation,
  useCreateUnitCardVersionMutation,
  useCurrentUnitCardsQuery,
  useDeleteEmptyUnitCardsMutation,
  usePreviewUnitCardMutation,
  useUnitCardByIdQuery,
  useUnitCardsByIdsQuery,
} from './unitCards';

export {
  armyKeys,
  commandCardKeys,
  unitCardKeys,
  ownedArmiesQueryOptions,
  ownedArmyByIdQueryOptions,
  useArchiveOwnedArmyMutation,
  useCreateOwnedArmyMutation,
  useOwnedArmiesQuery,
  useOwnedArmyByIdQuery,
  useUpdateOwnedArmyMutation,
  useCreateVsBotGameMutation,
  allCommandCardsQueryOptions,
  commandCardByIdQueryOptions,
  commandCardsByIdsQueryOptions,
  currentCommandCardsQueryOptions,
  useAllCommandCardsQuery,
  useCertifyLatestCommandCardVersionsMutation,
  useCommandCardByIdQuery,
  useCommandCardsByIdsQuery,
  useCreateCommandCardVersionMutation,
  useCreateEmptyCommandCardMutation,
  useCurrentCommandCardsQuery,
  useDeleteEmptyCommandCardsMutation,
  usePreviewCommandCardMutation,
  allUnitCardsQueryOptions,
  currentUnitCardsQueryOptions,
  unitCardByIdQueryOptions,
  unitCardsByIdsQueryOptions,
  useAllUnitCardsQuery,
  useCertifyLatestUnitCardVersionsMutation,
  useCreateEmptyUnitCardMutation,
  useCreateUnitCardVersionMutation,
  useCurrentUnitCardsQuery,
  useDeleteEmptyUnitCardsMutation,
  usePreviewUnitCardMutation,
  useUnitCardByIdQuery,
  useUnitCardsByIdsQuery,
};
