import { AuthContext, useAuth, useAuthPort } from './authContext';
import type { AuthViewModel } from './authContext';
import {
  useArmyEditor,
  useCommandCardEditor,
  useUnitCardEditor,
  unitArtworkUrlFromInput,
  isGameModeName,
  validateArmyForMode,
  validateArmyShape,
} from './authoring';
import type {
  ArmyBudgetProjection,
  ArmyDraft,
  ArmyDraftValidationResult,
  UseArmyEditorResult,
} from './authoring';
import { createCore } from './bootstrap';
import type { Core } from './bootstrap';
import { CoreProvider, useCore } from './coreContext';
import {
  boardSpaceToCellView,
  createGameStateProjections,
  createGameStateStore,
  gameOutcomeDetail,
  gameOutcomeFromState,
  gameOutcomeHeadline,
  phaseLabel,
  playerSideLabel,
  projectBoardCells,
  resolveUnitArtSrc,
  unitInstanceLabel,
} from './gameState';
import type {
  BoardCellView,
  BoardUnitView,
  GameOutcome,
  GameStateIngest,
  GameStateProjections,
  GameStateStore,
  PhaseSummary,
} from './gameState';
import {
  allCommandCardsQueryOptions,
  allUnitCardsQueryOptions,
  armyKeys,
  commandCardKeys,
  commandCardByIdQueryOptions,
  commandCardsByIdsQueryOptions,
  currentCommandCardsQueryOptions,
  currentUnitCardsQueryOptions,
  ownedArmiesQueryOptions,
  ownedArmyByIdQueryOptions,
  unitCardByIdQueryOptions,
  unitCardKeys,
  unitCardsByIdsQueryOptions,
  useAllCommandCardsQuery,
  useAllUnitCardsQuery,
  useArchiveOwnedArmyMutation,
  useCertifyLatestCommandCardVersionsMutation,
  useCertifyLatestUnitCardVersionsMutation,
  useCommandCardByIdQuery,
  useCommandCardsByIdsQuery,
  useCreateCommandCardVersionMutation,
  useCreateEmptyCommandCardMutation,
  useCreateEmptyUnitCardMutation,
  useCreateOwnedArmyMutation,
  useCreateVsBotGameMutation,
  useCreateUnitCardVersionMutation,
  useCurrentCommandCardsQuery,
  useCurrentUnitCardsQuery,
  useDeleteEmptyCommandCardsMutation,
  useDeleteEmptyUnitCardsMutation,
  useOwnedArmiesQuery,
  useOwnedArmyByIdQuery,
  usePreviewCommandCardMutation,
  usePreviewUnitCardMutation,
  useUnitCardByIdQuery,
  useUnitCardsByIdsQuery,
  useUpdateOwnedArmyMutation,
} from './queries';
import {
  ServerPortsContext,
  useArmies,
  useCommandCards,
  useGameSeat,
  useGames,
  useServerPorts,
  useUnitCards,
} from './serverPortsContext';
import {
  assignUnitSupportHint,
  boardProgressHint,
  choiceInstruction,
  commitHint,
  computeHighlights,
  connectionStatusLabel,
  formatCardEconomyMeter,
  formatCombatEngagementLine,
  formatCommitmentStatus,
  formatCommandLabel,
  formatPressureChip,
  isCommitChoiceType,
  legalOptionsForSeat,
  routDiscardHint,
  seatCommitmentSideLabel,
  setupUnitsByType,
  unitKey,
  useSeatPlaySession,
  waitHint,
} from './play';
import type {
  CardEconomyView,
  CellHighlight,
  ChoiceListItem,
  CombatContextView,
  IssuedCommandView,
  PlayBoardCellView,
  PlayCardSlotView,
  PlayHighlights,
  SeatSelection,
  SetupUnitTypeGroup,
  SideCardEconomy,
  UseSeatPlaySessionResult,
} from './play';
import { createRouteResponseError, isRouteResponseError } from '@ports';
import type { RouteResponseError } from '@ports';
import { createGameStorage } from './repositories';
import { useGreetMsg, useName } from './signals';

export {
  type AuthViewModel,
  AuthContext,
  useAuth,
  useAuthPort,
  useArmyEditor,
  useCommandCardEditor,
  useUnitCardEditor,
  unitArtworkUrlFromInput,
  isGameModeName,
  validateArmyForMode,
  validateArmyShape,
  type ArmyBudgetProjection,
  type ArmyDraft,
  type ArmyDraftValidationResult,
  type UseArmyEditorResult,
  type Core,
  createCore,
  CoreProvider,
  useCore,
  type BoardCellView,
  type BoardUnitView,
  type GameOutcome,
  type GameStateIngest,
  type GameStateProjections,
  type GameStateStore,
  type PhaseSummary,
  boardSpaceToCellView,
  createGameStateProjections,
  createGameStateStore,
  gameOutcomeDetail,
  gameOutcomeFromState,
  gameOutcomeHeadline,
  phaseLabel,
  playerSideLabel,
  projectBoardCells,
  resolveUnitArtSrc,
  unitInstanceLabel,
  allCommandCardsQueryOptions,
  allUnitCardsQueryOptions,
  armyKeys,
  commandCardKeys,
  commandCardByIdQueryOptions,
  commandCardsByIdsQueryOptions,
  currentCommandCardsQueryOptions,
  currentUnitCardsQueryOptions,
  ownedArmiesQueryOptions,
  ownedArmyByIdQueryOptions,
  unitCardByIdQueryOptions,
  unitCardKeys,
  unitCardsByIdsQueryOptions,
  useAllCommandCardsQuery,
  useAllUnitCardsQuery,
  useArchiveOwnedArmyMutation,
  useCertifyLatestCommandCardVersionsMutation,
  useCertifyLatestUnitCardVersionsMutation,
  useCommandCardByIdQuery,
  useCommandCardsByIdsQuery,
  useCreateCommandCardVersionMutation,
  useCreateEmptyCommandCardMutation,
  useCreateEmptyUnitCardMutation,
  useCreateOwnedArmyMutation,
  useCreateVsBotGameMutation,
  useCreateUnitCardVersionMutation,
  useCurrentCommandCardsQuery,
  useCurrentUnitCardsQuery,
  useDeleteEmptyCommandCardsMutation,
  useDeleteEmptyUnitCardsMutation,
  useOwnedArmiesQuery,
  useOwnedArmyByIdQuery,
  usePreviewCommandCardMutation,
  usePreviewUnitCardMutation,
  useUnitCardByIdQuery,
  useUnitCardsByIdsQuery,
  useUpdateOwnedArmyMutation,
  ServerPortsContext,
  useArmies,
  useCommandCards,
  useGameSeat,
  useGames,
  useServerPorts,
  useUnitCards,
  computeHighlights,
  formatCardEconomyMeter,
  formatCombatEngagementLine,
  formatCommitmentStatus,
  formatCommandLabel,
  isCommitChoiceType,
  legalOptionsForSeat,
  assignUnitSupportHint,
  boardProgressHint,
  commitHint,
  choiceInstruction,
  routDiscardHint,
  waitHint,
  connectionStatusLabel,
  formatPressureChip,
  seatCommitmentSideLabel,
  setupUnitsByType,
  unitKey,
  useSeatPlaySession,
  type CardEconomyView,
  type CellHighlight,
  type ChoiceListItem,
  type CombatContextView,
  type IssuedCommandView,
  type PlayBoardCellView,
  type PlayCardSlotView,
  type PlayHighlights,
  type SeatSelection,
  type SetupUnitTypeGroup,
  type SideCardEconomy,
  type UseSeatPlaySessionResult,
  type RouteResponseError,
  createRouteResponseError,
  isRouteResponseError,
  createGameStorage,
  useGreetMsg,
  useName,
};
